### PR TITLE
added all the classes

### PR DESCRIPTION
**Pull request by JosephMcArthur**
@markmacgillivray can you check this class code?

### CODE REVIEW

**Comment by markmacgillivray** [comment]
The class names you have added would work, but you have added them to divs inside col divs. This means that whilst the content of the div with the oa or od on it would disappear, the parent col div would not. So you would end up with for example a col-md-3 div with nothing in it, leaving a blank space on the page, and then the next col-md-3 with stuff in it. 

Also it is a bit odd how row divs and col divs are being used here - usually the idea is you use enough col divs to add up to twelve overall within a row. You CAN put more than that in, and they will just cascade further down the page usually quite neatly, but it is not strictly correct, so should usually only be done that way when you need to do so for some reason. Is that your intention here? If not, it may cause oddities when your page is rendered.

Also of course if you are hiding particular col divs within a given row, then that row would end up with say four col divs but two hidden, so you would have half of that row page empty. This is the sort of case where having more cols within a row div can help, but it is usually still neater and easier to fill rows with info about one sort of thing, e.g. all oa cards in a row, then just put the oa class on the containing row.

Finally where did you get card classes from? They appear to be a newer feature in bootstrap - we did discuss moving to bootstrap 4, although it has not been done yet. What sort of end result are you aiming for with those?

**Comment by JosephMcArthur** [comment]
> The class names you have added would work, but you have added them to divs inside col divs. This means that whilst the content of the div with the oa or od on it would disappear, the parent col div would not. So you would end up with for example a col-md-3 div with nothing in it, leaving a blank space on the page, and then the next col-md-3 with stuff in it.

Can fix this. 

> Also it is a bit odd how row divs and col divs are being used here - usually the idea is you use enough col divs to add up to twelve overall within a row. You CAN put more than that in, and they will just cascade further down the page usually quite neatly, but it is not strictly correct, so should usually only be done that way when you need to do so for some reason. Is that your intention here? If not, it may cause oddities when your page is rendered.

Also of course if you are hiding particular col divs within a given row, then that row would end up with say four col divs but two hidden, so you would have half of that row page empty. This is the sort of case where having more cols within a row div can help, but it is usually still neater and easier to fill rows with info about one sort of thing, e.g. all oa cards in a row, then just put the oa class on the containing row.

They should be arranged so that they add up to 12 at the moment. Not sure why that isn't the case. However, it seems like removing the rows entirely might be a good way to go with the current pages style. I'll do that now.

> Finally where did you get card classes from? They appear to be a newer feature in bootstrap - we did discuss moving to bootstrap 4, although it has not been done yet. What sort of end result are you aiming for with those?

@mtb-za did them a long time ago. We wanted card-like things. Not sure if he was expecting for them to actually use bootstrap 4 though.

**Comment by markmacgillivray** [comment]
Removing rows entirely will change the amount of padding around objects on
the page though, so it is best to use rows so that page layout matches
other pages. However just put more col divs in as necessary. Maybe they do
already add up to twelve, I was just not sure if you were aware of the
reasoning.

If the card classes are just from the old site content, they may not work
on the new site - I do not know if we have that css on the new site.
However just put in what you need for now and I can fix later if necessary,
either changing classes or getting the old css.

**Comment by JosephMcArthur** [comment]
Hey Mark, I've changed:

* where the classes are to address the above. 
* card sizes to have 3 per line
* checked rows add up to 12
* commented the whole document to make structure clearer
* tried to remove excess divs where they're available. I tried to make sure each div lined up with where I expected (use the blue underlines on atom). 
* removed style code not in use
* added the map embed at the top. Had to guess some code changes for it.

so there are now many changes.

**Pull request merged**
