### PR TITLE
update terms to remove reference to password

### PR DESCRIPTION
**Pull request by JosephMcArthur**
also cleaned double spaces & formalised

### CODE REVIEW

**Comment by JosephMcArthur** [comment]
@chealsye I've made changes to these policies - can you proof read them please? changes are itemised here: https://github.com/OAButton/oab_static/pull/23/files

**Comment by JosephMcArthur** [comment]
Did you check the copy for this?

**Comment by chealsye** [comment]
I'm reading through it now - reading it in github wasn't going to be fun.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you resolve these conflicts & merge asap

**Comment by markmacgillivray** [comment]
Sorry, no. When a merge fails at this point, it is before the codeship push has occurred. This is not a conflict with something I have on the dev system, it is a conflict between the new copy and the old copy within the branches that are being merged. This means at some point someone has changed the develop branch copy before the other branch has been merged in, in such a way that the two are incompatible. In order to fix it I would need to know which copy is correct and which is not. This would be better done by someone who knows which copy was intended, and which was not.

Here are the instructions for solving merge conflicts:

**Comment by markmacgillivray** [comment]
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by JosephMcArthur** [comment]
Essentially this branch represents the state of these two files that should be on develop ( I move changes over earlier this eve). 

I can't do the command line stuff (will learn soon, just not now) so will just brute force it by copy & pastes the changes if I haven't provided enough info above.

**Comment by markmacgillivray** [comment]
So the stuff in the branch being merged in should overwrite what is in
develop, no matter what? If so, I can do that for you.

**Comment by JosephMcArthur** [comment]
Yes. As long as it's only for /privacy & /terms.

**Pull request merged**
